// Package port provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package port

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code The HTTP status code.
	Code int `json:"code"`

	// Message A descriptive error message.
	Message string `json:"message"`
}

// HealthCheckResponse defines model for HealthCheckResponse.
type HealthCheckResponse struct {
	// Status The health check status (e.g., "ok", "error").
	Status string `json:"status"`

	// Timestamp The current timestamp in ISO 8601 format.
	Timestamp time.Time `json:"timestamp"`
}

// User defines model for User.
type User struct {
	// ID The user identifier.
	ID int `json:"id"`

	// Name The user name.
	Name string `json:"name"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	// Name The user name.
	Name string `json:"name"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	// Items The list of users.
	Items []User `json:"items"`

	// Limit The limit of items which returned per request.
	Limit int `json:"limit"`

	// Skip The amount of items to skip.
	Skip int `json:"skip"`

	// TotalItems The total items.
	TotalItems int `json:"totalItems"`
}

// GetUserListParams defines parameters for GetUserList.
type GetUserListParams struct {
	// Limit The limit of items which returned per request.
	Limit int `form:"limit" json:"limit"`

	// Skip The amount of items to skip.
	Skip int `form:"skip" json:"skip"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreateRequest
